//CONTEXT TYPES
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";

//MENU
export const SET_ACTIVE_MENU = "SET_ACTIVE_MENU";
export const PREVIOUS_MENU = "PREVIOUS_MENU";

//SINGLE PLAYER GAME ACTIONS
export const CREATE_SINGLE_PLAYER = "CREATE_SINGLE_PLAYER";
export const START_SINGLE_PLAYER = "START_SINGLE_PLAYER";
export const END_SINGLE_PLAYER = "END_SINGLE_PLAYER";
export const SCORE_SINGLE_PLAYER = "SCORE_SINGLE_PLAYER";

//MULTI PLAYER GAME ACTIONS
export const UPDATE_SOCKET_ID = "UPDATE_SOCKET_ID";
export const JOIN_LOBBY = "JOIN_LOBBY";
export const UPDATE_LOBBY = "UPDATE_LOBBY";
export const LEAVE_LOBBY = "LEAVE_LOBBY";
export const UPDATE_USER_READY = "UPDATE_USER_READY";
export const UPDATE_LOBBY_GAME_STATE = "UPDATE_LOBBY_GAME_STATE";

//SETTINGS
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const SAVE_GAME_SETTINGS = "SAVE_GAME_SETTINGS";
