//CONTEXT TYPES
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const CHANGE_THEME = "CHANGE_THEME";

export const SET_ACTIVE_MENU = "SET_ACTIVE_MENU";
export const PREVIOUS_MENU = "PREVIOUS_MENU";
//GAME DISPLAY FUNCTIONS
export const RANDOMIZE_CARD_GRID = "RANDOMIZE_CARD_GRID";

//SINGLE PLAYER GAME FUNCTIONS
export const CREATE_SINGLE_PLAYER = "CREATE_SINGLE_PLAYER";
export const START_SINGLE_PLAYER = "START_SINGLE_PLAYER";
export const END_SINGLE_PLAYER = "END_SINGLE_PLAYER";
export const SCORE_SINGLE_PLAYER = "SCORE_SINGLE_PLAYER";

//MULTI PLAYER GAME FUNCTIONS
export const UPDATE_SOCKET_ID = "UPDATE_SOCKET_ID";
