//CONTEXT TYPES
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
export const CHANGE_THEME = "CHANGE_THEME";

export const SET_ACTIVE_MENU = "SET_ACTIVE_MENU";
//GAME DISPLAY FUNCTIONS
export const RANDOMIZE_CARD_GRID = "RANDOMIZE_CARD_GRID";
